# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/dhconnelly/rtreego"

[[constraint]]
  branch = "master"
  name = "github.com/gen1us2k/go-translit"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/kellydunn/golang-geo"
  version = "0.7.0"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.1.8"

[[constraint]]
  name = "github.com/paulmach/go.geo"
  version = "0.1.0"

[[constraint]]
  name = "github.com/paulmach/go.geojson"
  version = "1.3.1"

[[constraint]]
  name = "github.com/qedus/osmpbf"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v3"
  version = "3.0.73"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
